
# Poverty line 
POVERTY_LINE = 1

# 1KM
MAX_DISTANCE = 0.002

# minimum flood depth to be considered as a flood
FLOOD_DAMAGE_THRESHOLD = 100
FLOOD_DAMAGE_MAX = 1000
FLOOD_FEAR_MAX = 300

DISPLACE_DAMAGE_THRESHOLD = 0.65


STATUS_NORMAL = 'normal'
STATUS_EVACUATED = 'evacuated'
STATUS_DISPLACED = 'displaced'
STATUS_TRAPPED = 'trapped'

MATERIAL_STONE_BRICKS = 'Stone bricks'
MATERIAL_CONCRETE = 'Concrete'
MATERIAL_WOOD = 'Wood'
MATERIAL_MUD_BRICKS = 'Mud bricks'
MATERIAL_INFORMAL_SETTLEMENTS = 'Informal settlement'

