
# Poverty line 
POVERTY_LINE = 25000

# 1KM
MAX_DISTANCE = 0.002

# minimum flood depth to be considered as a flood
FLOOD_DAMAGE_THRESHOLD = 100
FLOOD_DAMAGE_MAX = 1000
FLOOD_FEAR_MAX = 300

DISPLACE_DAMAGE_THRESHOLD = 0.65


STATUS_NORMAL = 'normal'
STATUS_EVACUATED = 'evacuated'
STATUS_DISPLACED = 'displaced'
STATUS_TRAPPED = 'trapped'

MATERIAL_STONE_BRICKS = 'Stone bricks'
MATERIAL_CONCRETE = 'Concrete'
MATERIAL_WOOD = 'Wood'
MATERIAL_MUD_BRICKS = 'Mud bricks'
MATERIAL_INFORMAL_SETTLEMENTS = 'Informal settlement'

CHECK_TRUST = False
# -----------------
# trap probability params
HEALTH_COEFFIECIENT = -0.6068767
LN_INCOME_COEFFIECIENT = 0.4817414
OWN_HOUSE_COEFFIECIENT = -0.7235926
OWN_CROPS_COEFFIECIENT = -0.2117797
OWN_CATTLES_COEFFIECIENT = 0.9470529


AL_GAILI_COEFFIECIENT = -5.95
AL_SHUHADA_COEFFIECIENT = -5.80
ELTOMANIAT_COEFFIECIENT = -8.15
WAD_RAMLI_COEFFIECIENT = -7.22
WAWISE_GARB_COEFFIECIENT = -7.16
WAWISE_OUM_OJAIJA_COEFFIECIENT = -4.47

#------------

BASE_RECOVERY = 0.30

# threshold used to decide whether to 
# increase awareness or not when checking for 
# neighbours damage
NEIGHBOURS_HIGH_DAMAGE_FRACTION = 0.25

TRUST_THRESHOLD = 0.5
RISK_PERCEPTION_THRESHOLD = 0.5
LOW_DAMAGE_THRESHOLD = 0.25
HIGH_DAMAGE_THRESHOLD = 0.60
TRUST_CHANGE = 0.1
FEAR_CHANGE = 0.1
AWARENESS_DECREASE = 0.1
AWARENESS_INCREASE = 0.4

FIX_DAMAGE_NEIGHBOURS = 0.05
FIX_DAMAGE_CONCRETE = 0.3
FIX_DAMAGE_MUDBRICK = 0.4
FIX_DAMAGE_INFORMAL_SETTLEMENT = 0.5